version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_estacionamento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: estacionamento
      MYSQL_DATABASE: Estacionamento
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
